#! /usr/bin/python3

class MultiDict:
    def __init__(self, d={}):
        self._layer1 = {}
        self._layer2 = {}
        # Expects input in the form {(k1a, k1b): v1, (k2a): v2} (a dictionary
        # of tuples-to-values)
        # For that matter a dict of lists-to-values works too
        # The basic idea is that it maps all members of a given key to the 
        # first element of that key, which is used as the key to the second
        # mapping which actually contains the values.
        # The fundamental operations on this object will be these:
        #  1. multidict[k] = v
        #     Sets key group containing k to value v.
        #     If key belongs to no key group, create a new key group containing
        #     only k and set its value to v.
        #  2. multidict.join(k1, k2) joins k1 to the key group containing k2.
        #     That is all it does; even if k1 originally belongs to (k1, k3),
        #     k3 is unaffected besides k1 being removed from its group.
        # Construction of this object will be considered like so:
        #  1. A key tuple-or-list of the form (k1a, k1b, ...): v1 will be 
        #     treated as:
        #     if a key group already contains k1a:
        #       multidict[k1a] = v1
        #     else if no key group already contains k1a:
        #       multidict[k1a] = v1
        #     Oh I guess multidict[k] takes care of this already.
        #     Anyway the rest would be:
        #     multidict.join(k1b, k1a)
        #     multidict.join(..., k1a or k1b or any other key in that key group 
        #       it doesn't matter)
        # For example: {(k1a, k1b): v1, (k1b): v2} would create self._layer1 
        # and _layer2 as follows:
        #  1. Key is (k1a, k1b). Value is v1.
        #     This should create a new key group containing k1a and then join
        #     k1b to it.
        #     md[k1a] = v1:
        #     self._layer1 = {k1a: k1a}
        #     self._layer2 = {k1a: v1}
        #     md.join(k1b, k1a):
        #     self._layer1 = {k1a: k1a, k1b: k1a}
        #  2. Key is (k1b). Value is v2.
        #     This should set key group containing k1b to the value v2.
        #     md[k1b] = v2:
        #     self._layer1 = {k1a: k1a, k1b: k1a} (no change)
        #     self._layer2 = {k1a: v2}
        for k in d:
            for i in range(len(k)):
                subkey = k[i]
                if i==0:
                    # become the "root node" of this key-set
                    rootkey = subkey
                    self.__setitem__(subkey, d[k])
                else:
                    self.join(subkey, rootkey)

    def __repr__(self):
        # TODO iterator for MultiDict
        # YIKES I have to build these darn things in reverse
        # I mean seriously if the number of keys is N and the number of values/
        # groups is M this is going to take O(N*M) time.
        diclist = {}
        for rootkey in self._layer2:
            val = self._layer2[rootkey]
            for key in self._layer1:
                if self._layer1[key] == rootkey:
                    if val in diclist:
                        diclist[val].append(key)
                    else:
                        diclist[val] = [key]

        out = "{"
        for val in diclist:
            out = out + str(tuple(diclist[val]))
            out = out + ": " + repr(val) + ", "
        out = out + "}"

        return out

    def __setitem__(self, key, value):
        if key in self._layer1:
            self._layer2[self._layer1[key]] = value
        else:
            self._layer1[key] = key
            self._layer2[self._layer1[key]] = value
                
    def __getitem__(self, key):
        if key in self._layer1:
            return self._layer2[self._layer1[key]]
        else:
            raise KeyError()

    def __contains__(self, key):
        return key in self._layer1

    #def
    # TODO do __delitem__ and __keys__ and stuff later

    def join(self, key_wanting_to_join, key_dest):
        self._layer1[key_wanting_to_join] = self._layer1[key_dest]
        # TODO do something if a key group no longer has members
            
class TrackSeg:
    def __init__(self, index, start, end, speed):
        assert index >= 0 and type(index) is int
        assert start <= end
        assert speed >= 0
        self._index = index
        self._start = int(start)
        self._end   = int(end)
        self._speed = speed
    
    def __str__(self):
        return "id: {}, {} mi - {} mi @ {:.1f} mph".format(self._index, self._start/5280, self._end/5280, self._speed*3600/5280)
    
    def __repr__(self):
        return "TrackSeg(index={}, start={}, end={}, speed={})".format(self._index, self._start, self._end, self._speed)
    
    def get_index(self):
        return self._index
    
    def get_start(self):
        return self._start
    
    def get_end(self):
        return self._end
    
    def get_speed(self):
        return self._speed
    
    def length(self):
        return self._end - self._start
    
class Track:
    from collections import namedtuple
    MaxSpeed = namedtuple("MaxSpeed", ["milepost", "speed"])

    def __init__(self, filename):
        # load the file into TrackSegs into
        self._track = self._load_maxspeeds(filename)
        # and throw if anything goes wrong
        assert len(self._track) > 0, "there must be at least one track segment"

    def __str__(self):
        out = "[\n"
        for seg in self._track:
            out += str(seg) + "\n"
        out += "]"
        return out

    def get_first_seg(self):
        return self._track[0]

    # throws IndexError and AssertionError
    def get_next_seg(self, index, direction):
        assert direction == "+" or direction == "-"
        if direction == "+": d = 1
        elif direction == "-": d = -1
        
        if index + d < 0: raise IndexError("Next segment index out of bounds")

        return self._track[index + d]

    def _load_maxspeeds(self, filename):
        import csv
        raw_maxspeeds = [maxspeed for maxspeed in map (self.MaxSpeed._make, csv.reader(open(filename, "r"), delimiter='	', quoting=csv.QUOTE_NONNUMERIC))]
        
        # generate segments from that
        maxspeedsegs = []
        for x in range(0, len(raw_maxspeeds)-1):
            maxguy = raw_maxspeeds[x]
            mp1 = maxguy.milepost * 5280
            maxguy2 = raw_maxspeeds[x+1]
            mp2 = maxguy2.milepost * 5280
            #if maxguy2.speed != 0:
            seg = TrackSeg(x, mp1, mp2, maxguy.speed * 5280 / 3600)
            if (x+1 == len(raw_maxspeeds)-1):
                seg = TrackSeg(x, mp1, mp2, maxguy2.speed * 5280/3600)
            maxspeedsegs.append(seg)

        return maxspeedsegs
 
class Train:
    def __init__(self, track, acceleration, resolution):
        assert acceleration > 0
        assert resolution > 0 and type(resolution) is int
        self._track = track
        self._acceleration = acceleration
        self._resolution = resolution
        # then the derived attributes and defaults
        self._speed = 0
        self._seg = self._track.get_first_seg()
        self._pos = self._seg.get_start()
        self._dir = "+"
        self._finished_seg = False

    def __str__(self):
        return ("pos: {:.1f} mi, speed {:.2f} mph, dir: {}, seg: ({}), accel: {}, "+ \
            "res: {}, finished {}, track defined: {}").format(self._pos/5280, self._speed*3600/5280, self._dir, self._seg, self._acceleration, self._resolution, self._finished_seg, self._track is not None)

    def get_pos(self):
        return self._pos

    def get_speed(self):
        return self._speed

    def finished_seg(self):
        return self._finished_seg

    def at_end_of_track(self):
        assert self._dir == "+" or self._dir == "-"
        if self._dir == "+":
            try:
                self._track.get_next_seg(self._seg.get_index(), self._dir)
            except IndexError:
                # we must be at last segment already
                # check if we are at the end of it
                return self._pos == self._seg.get_end()
        else:
            return self._seg == self._track.get_first_seg() and self._pos == \
                self._seg.get_start()

    def set_dir(self, direction):
        assert direction == "+" or direction == "-"
        self._dir = direction
        self._finished_seg = False

    # kind of does everything
    # travels along 1 resolution of track each call
    # automatically loads the next TrackSeg when at end of current one
    # returns false when it's finished the last resolution-length in seg
    # (i.e. self._finished_seg == True I think)
    # (except when it's at end of last seg in track, in which case it returns
    # False even though self._finished_seg is True)
    # ...
    # I need to think this through better.
    def travel_seg(self):
        if self._finished_seg == True:
            # load next seg
            try:
                self._seg = self._track.get_next_seg(\
                    self._seg.get_index(), self._dir)
                self._finished_seg = False
            except IndexError:
                # must be at one end of the track
                return False
            #return True # not sure what this one was here for
    
        if self._finished_seg == False:
            if (self._seg.length() != 0):
                self._finished_seg = self._travel_non0_seg()
            else:
                self._speed = min(self._seg.get_speed(), self._speed)
                # well I guess we're instantly finished with a 0-length seg
                self._finished_seg = True

        return self._finished_seg

    # takes all units in feet units
    def _accelerate(self, v_target, acc, v_i, d):
        assert v_target >= 0 and v_i >= 0
        assert d >= 0
        assert acc > 0
        nacc = acc
        from math import sqrt
        t = ( -v_i + sqrt(v_i**2 - 4.0 * 0.5 * nacc * -d) ) / (2.0*0.5*nacc)
        v_f = nacc * t + v_i
        return v_f

    def _travel_non0_seg(self):
        assert self._seg.length() % self._resolution == 0

        # accelerate() over one resolution of distance? I didn't think 
        # this far ahead.
        segspeed = self._seg.get_speed()
        self._speed = min(segspeed, self._accelerate(segspeed, self._acceleration, self._speed, self._resolution))

        # always travels over seg at least *once*, even if zero-length
        assert self._dir == "+" or self._dir == "-"
        if self._dir == "+":
            self._pos += self._resolution
            if self._pos == self._seg.get_end():
                self._finished_seg = True
        elif self._dir == "-":
            self._pos -= self._resolution
            if self._pos == self._seg.get_start():
                self._finished_seg = True
        return self._finished_seg

class ArgvError(Exception):
    """ An error having to do with the command-line arguments """
    pass

class Config:
    class FlagDesc:
        def __init__(self, val, needs_val=True):
            self.val = val
            self.needs_val = needs_val

    def __init__(self, argv):
        self._flagsdict = MultiDict({("-u", "--units"): self.FlagDesc(None)})
        self._flagsdict["-b"] = self.FlagDesc(None, False)
        self._flagsdict.join("--boolean", "-b")
        self._flagsdict["-h"] = self.FlagDesc(None, False)
        self._flagsdict.join("--help", "-h")
        
        # declare what we're configuring (just to be clear)
        self.mode = None
        self.infile = None
        self.units = None

        self._parse(argv)
        self._validate_args()
    
    def _parse(self, argv):
        # input filename is just by itself, all other args are -<FLAG> val
        assert len(argv) > 1
        #for arg in argv[1:]:
        isflagval = False
        for arg in argv[1:]:
            if arg[0] == "-" and not isflagval: # it's a flag
                if arg in self._flagsdict:
                    if self._flagsdict[arg].needs_val:
                        flag = arg
                        isflagval = True # next argv entry must be a value
                    else:
                        self._flagsdict[arg].val = True
                else:
                    raise KeyError("No such flag")
            elif isflagval:
                if self._flagsdict[flag].val == None:
                    self._flagsdict[flag].val = arg
                    isflagval = False
                else:
                    raise ArgvError("Cannot define flag multiple times")
            else: # must be by itself (so probably input filename)
                if self.infile == None:
                    self.infile = arg
                else:
                    raise ArgvError("Cannot have multiple input files")
        
    def _validate_args(self):
        # make sure arguments are logical and consistent etc.
        if self._flagsdict["-h"].val == True:
            self.mode = "help"
        else:
            # default configuration or something
            self.mode = "sim"

        if self.mode == "sim":
            if self._flagsdict["-u"].val in [None, "imperial"]:
                self.units == "imperial"
            if self.infile == None:
                raise ArgvError("Must specify input file")

        if self.mode == "help":
            pass
       
    def gen_help(self):
        # generate this automagically from self._flagsdict later
        return  "trainspeedsim [-h|--help | [-u|--units UNIT] INPUT_FILE\n" + \
                "  -u|--units: imperial|metric"

class Simulation:
    from collections import namedtuple
    PosSpeed = namedtuple("PosSpeed", ["pos", "speed"])

    def __init__(self, filename, accel, resolution):
        assert accel > 0
        assert resolution > 0 and type(resolution) is int
        self._resolution = resolution
        self._track = Track(filename)
        self._train = Train(self._track, accel, self._resolution)
        self._best_speeds = []

    def run(self):

        fwd_best_speeds = self._gen_best_speeds_dir("+")
        
        rev_best_speeds = self._gen_best_speeds_dir("-")

        # note: all of that up there generated duplicate PosSpeeds for 0-length 
        # segments
        # we will need to fix this when building self._best_speeds

        lastps = None
        for paired in zip(fwd_best_speeds, reversed(rev_best_speeds)):
            assert paired[0].pos == paired[1].pos
            ps = self.PosSpeed(paired[0].pos, min(paired[0].speed, \
                paired[1].speed))
            if (lastps is None or (ps.pos != lastps.pos or ps.speed != lastps.speed)):
                self._best_speeds.append(ps)
            lastps = ps
            
    def output(self):
        for point in self._best_speeds:
            print("{:.1f}, {}".format(point.pos/5280, point.speed*3600/5280))
    
    def _gen_best_speeds_dir(self, direction):
        assert direction=="+" or direction=="-"
        best = []
        self._train.set_dir(direction)
        while not self._train.at_end_of_track():
            self._train.travel_seg()
            if not self._train.at_end_of_track(): # prevents repeating last seg
                best.append(self.PosSpeed(self._train.get_pos(), \
                    self._train.get_speed()))
        return best
        

if __name__ == "__main__":
    md = MultiDict({("k1a", "k1b"): "v1", ("k2a",): "v2"})

    print(md)

    md["k3a"] = "v3"

    print(md)

    md["k1b"] = 4

    print(md)

    # test if repr does the thing
    md2 = MultiDict(eval(repr(md)))
    print(md2)

    import sys
    conf = Config(sys.argv)

    if conf.mode == "sim":
        sim = Simulation(conf.infile, 1.25, 528)
        sim.run()
        sim.output()
    elif conf.mode == "help":
        print(conf.gen_help())
